# Generated by Django 5.1.4 on 2025-02-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_remove_payment_payment_date_alter_contract_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewee',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='freelancer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='contract',
        ),
    ]
