# Generated by Django 5.1.4 on 2025-02-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_review_options_remove_review_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
