# Generated by Django 5.1.4 on 2025-01-09 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'jobs_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'skills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.FloatField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('FIXED', 'Fixed Price'), ('HOURLY', 'Hourly Rate'), ('MILESTONE', 'Milestone Based'), ('PROJECT', 'Project Based')], max_length=20)),
                ('time_preferences_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('FLEXIBLE', 'Flexible Hours'), ('CONTRACT', 'Contract Based'), ('CUSTOM', 'CUSTOM')], max_length=20)),
                ('custom_time_preference', models.CharField(blank=True, help_text='Custom time preference if not selecting from predefined options', max_length=255, null=True)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry Level'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert'), ('ALL', 'All Levels')], max_length=20)),
                ('location', models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'On-site'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='user.profile')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.jobcategory')),
                ('skills', models.ManyToManyField(to='job.skill')),
            ],
            options={
                'db_table': 'jobs',
                'managed': True,
            },
        ),
    ]
